language: c

os:
    - linux
    - osx

before_install:
- curl -L https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh | sh

install:
- eval `opam config env`
- opam update
- opam upgrade
- opam install coq

script:
    make -j > /dev/null

env:
  global:
  - OCAML_VERSION=4.07
  - NJOBS=2
  - OPAMVERBOSE=1
  - OPAMYES=true

matrix:
  fast_finish: true
  allow_failures:
  - os: osx

before_cache:
- if [ $TRAVIS_OS_NAME = osx ]; then brew cleanup; fi
- opam clean

cache:
  apt: true
  directories:
  - $HOME/.opam
  - $HOME/Library/Caches/Homebrew
